// P5: the CMS API end to end in a Worker (`wrangler dev --local`, local D1 with the package migrations), publishing to
// a fake GitHub on 127.0.0.1. Runs test/helpers/api-scenario.mjs against it. Nothing remote; temp state is deleted.
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { contentPaths, loadCmsConfig } from "../dist/index.js";
import { runApiScenario } from "../test/helpers/api-scenario.mjs";
import { startFakeGitHub } from "../test/helpers/fake-github.mjs";
import { npx, startWranglerDev } from "./lib/wrangler-dev.mjs";

const cwd = fileURLToPath(new URL("../test/api-worker/", import.meta.url));
const demoRoot = fileURLToPath(new URL("../fixtures/demo-site/", import.meta.url));
const config = await loadCmsConfig(join(demoRoot, "cms.config.ts"));
const files = Object.fromEntries(contentPaths(config, demoRoot).map((path) => [path, readFileSync(join(demoRoot, path), "utf8")]));
writeFileSync(join(cwd, "generated.mjs"), `// Generated by scripts/api-local.mjs (not committed): the demo site's config and content.\nexport const config = ${JSON.stringify(config)};\nexport const files = ${JSON.stringify(files)};\n`);

const github = await startFakeGitHub({ owner: config.repo.owner, name: config.repo.name, branch: config.repo.branch, files });
const persist = mkdtempSync(join(tmpdir(), "vibe-cms-api-"));
try {
  const applied = npx(["wrangler", "d1", "migrations", "apply", "DB", "--local", "--persist-to", persist, "--config", "wrangler.jsonc"], { cwd, input: "y\n" });
  assert.equal(applied.status, 0, `migrations apply failed:\n${applied.stdout}\n${applied.stderr}`);
  const { base, stop } = await startWranglerDev({ cwd, config: "wrangler.jsonc", ready: "/api/cms/live-version", args: ["--persist-to", persist, "--var", `GITHUB_API:${github.url}`, "--var", `GITHUB_TOKEN:${github.token}`] });
  try {
    const origin = new URL(base).origin;
    const request = async (method, path, { body, user, origin: from = origin, raw } = {}) => {
      const headers = { ...(user ? { "x-test-user": user } : {}), ...(from ? { origin: from } : {}) };
      const init = { method, headers };
      if (raw !== undefined || body !== undefined) { init.body = raw ?? JSON.stringify(body); headers["content-type"] = "application/json"; }
      const response = await fetch(`${base}${path}`, init);
      const text = await response.text();
      let parsed; try { parsed = JSON.parse(text); } catch { parsed = { raw: text.slice(0, 300) }; }
      return { status: response.status, body: parsed, headers: Object.fromEntries(response.headers) };
    };
    const checks = await runApiScenario({
      request, github,
      redeploy: async () => { await fetch(`${base}/__test/redeploy`); },
      auditRows: async () => (await (await fetch(`${base}/__test/audit`)).json()).reverse(),
    });
    const failed = checks.filter((check) => !check.ok);
    assert.deepEqual(failed, [], "every API check passes in wrangler dev --local");
    console.log(`API (wrangler dev --local, D1 + fake GitHub) OK: ${checks.length} checks passed; ${github.requests.filter((r) => r.method === "PATCH").length} branch updates tried, ${github.forcedUpdates()} forced.`);
  } finally { stop(); }
} finally {
  await github.close();
  rmSync(persist, { recursive: true, force: true });
  rmSync(join(cwd, "generated.mjs"), { force: true });
}
process.exit(0);
