// P6: sign-in + People + the P5 publish flow with a REAL sign-in, in a Worker under `wrangler dev --local` (local D1 with
// the package migrations, local KV, local rate-limit bindings), publishing to a fake GitHub on 127.0.0.1. Also times a
// sign-in (PBKDF2 100k) against a cheap request. Nothing remote; temp state is deleted. Test values only.
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { contentPaths, loadCmsConfig } from "../dist/index.js";
import { lineDiff } from "../test/helpers/diff.mjs";
import { startFakeGitHub } from "../test/helpers/fake-github.mjs";
import { npx, startWranglerDev } from "./lib/wrangler-dev.mjs";

const cwd = fileURLToPath(new URL("../test/auth-worker/", import.meta.url));
const demoRoot = fileURLToPath(new URL("../fixtures/demo-site/", import.meta.url));
const config = await loadCmsConfig(join(demoRoot, "cms.config.ts"));
const files = Object.fromEntries(contentPaths(config, demoRoot).map((path) => [path, readFileSync(join(demoRoot, path), "utf8")]));
writeFileSync(join(cwd, "generated.mjs"), `// Generated by scripts/auth-local.mjs (not committed).\nexport const config = ${JSON.stringify(config)};\nexport const files = ${JSON.stringify(files)};\n`);

const BOOT = { username: "owner", password: "bootstrap-test-secret" };
const github = await startFakeGitHub({ owner: config.repo.owner, name: config.repo.name, branch: config.repo.branch, files });
const persist = mkdtempSync(join(tmpdir(), "vibe-cms-auth-"));
const checks = [];
const check = (name, ok, detail) => { checks.push({ name, ok: Boolean(ok) }); if (!ok) console.error(`✘ ${name}\n${JSON.stringify(detail ?? null).slice(0, 1500)}`); };
try {
  const applied = npx(["wrangler", "d1", "migrations", "apply", "CMS_DB", "--local", "--persist-to", persist, "--config", "wrangler.jsonc"], { cwd, input: "y\n" });
  assert.equal(applied.status, 0, `migrations apply failed:\n${applied.stdout}\n${applied.stderr}`);
  const vars = { GITHUB_API: github.url, VIBE_GITHUB_TOKEN: github.token, CMS_BOOTSTRAP_USERNAME: BOOT.username, CMS_BOOTSTRAP_PASSWORD: BOOT.password };
  const { base, stop } = await startWranglerDev({ cwd, config: "wrangler.jsonc", ready: "/api/auth/me", args: ["--persist-to", persist, ...Object.entries(vars).flatMap(([key, value]) => ["--var", `${key}:${value}`])] });
  try {
    const origin = new URL(base).origin;
    let ip = 0;
    const call = async (method, path, { body, cookie, from = origin, clientIp = `192.0.2.${(ip = (ip % 250) + 1)}` } = {}) => {
      const headers = { "cf-connecting-ip": clientIp, ...(from ? { origin: from } : {}), ...(cookie ? { cookie: `vibe_cms_session=${cookie}` } : {}), ...(body === undefined ? {} : { "content-type": "application/json" }) };
      const started = performance.now();
      const response = await fetch(`${base}${path}`, { method, headers, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
      const ms = performance.now() - started;
      const text = await response.text();
      let parsed; try { parsed = JSON.parse(text); } catch { parsed = { raw: text.slice(0, 200) }; }
      return { status: response.status, body: parsed, ms, cookie: /vibe_cms_session=([^;]*)/.exec(response.headers.get("set-cookie") ?? "")?.[1] || undefined, headers: Object.fromEntries(response.headers) };
    };
    const login = (username, password, options) => call("POST", "/api/auth/login", { body: { username, password }, ...options });

    // Sign-in, bootstrap, first password
    const anonymous = await call("GET", "/api/cms/content");
    check("no session → 401", anonymous.status === 401 && anonymous.body.error === "unauthenticated", anonymous);
    const first = await login(BOOT.username, BOOT.password);
    check("bootstrap sign-in creates the owner (must change password)", first.status === 200 && first.body.user.role === "owner" && first.body.mustChangePassword === true, first);
    check("…content is refused until the password is changed", (await call("GET", "/api/cms/content", { cookie: first.cookie })).body.error === "password_change_required");
    const ownerCookie = (await call("PUT", "/api/auth/password", { cookie: first.cookie, body: { currentPassword: BOOT.password, newPassword: "owner-password-456" } })).cookie;
    check("after changing it: old session 401, new session 200", (await call("GET", "/api/cms/content", { cookie: first.cookie })).status === 401 && (await call("GET", "/api/cms/content", { cookie: ownerCookie })).status === 200);
    check("bootstrap secrets no longer sign in", (await login(BOOT.username, BOOT.password)).status === 401);
    check("sign-in from another origin → 403", (await login("owner", "owner-password-456", { from: "https://evil.example" })).body.error === "origin_forbidden");

    // People
    const created = await call("POST", "/api/cms/users", { cookie: ownerCookie, body: { username: "editor1", displayName: "Editor One", role: "editor" } });
    check("owner adds an editor → 201 + temporary password", created.status === 201 && /^[A-Za-z2-9]{20}$/.test(created.body.temporaryPassword ?? ""), created);
    const editorFirst = await login("editor1", created.body.temporaryPassword);
    const editorCookie = (await call("PUT", "/api/auth/password", { cookie: editorFirst.cookie, body: { currentPassword: created.body.temporaryPassword, newPassword: "editor-password-789" } })).cookie;
    check("editor on People → 403 owner_only", (await call("GET", "/api/cms/users", { cookie: editorCookie })).body.error === "owner_only");
    const me = await call("GET", "/api/auth/me", { cookie: editorCookie });
    check("/me: the editor, internal id, no hash", me.body.user?.role === "editor" && /^usr_/.test(me.body.user.id) && !JSON.stringify(me.body).includes("pbkdf2"), me);

    // The P5 flow with a real sign-in: draft → publish → one commit, one line; locked field refused for the editor
    const site = (await call("GET", "/api/cms/files/site", { cookie: editorCookie })).body;
    const locked = await call("PUT", "/api/cms/files/site", { cookie: editorCookie, body: { content: { ...site.content, phone: "(555) 999-0000" }, expectedRevision: 0, sourceVersion: site.version } });
    check("editor changing Phone → 403 locked_field", locked.body.error === "locked_field", locked);
    const saved = await call("PUT", "/api/cms/files/site", { cookie: editorCookie, body: { content: { ...site.content, tagline: "Signed-in edit" }, expectedRevision: 0, sourceVersion: site.version } });
    check("editor saves a draft", saved.status === 200 && saved.body.draft.revision === 1, saved);
    const head = github.head();
    const before = github.files()["src/data/site.json"];
    const published = await call("POST", "/api/cms/publish", { cookie: editorCookie, body: { resources: ["file:site"] } });
    const diff = lineDiff(before, github.files()["src/data/site.json"]);
    check("publish with a real session → 1 commit, 1 changed line", published.status === 200 && github.commitsSince(head).length === 1 && diff.removed.length === 1 && diff.added.length === 1, { published, diff });
    check("…commit message carries the editor's internal id, no email", github.commit().message.includes(me.body.user.id) && !github.commit().message.includes("@"));

    // Disable → at once; last owner
    await call("PATCH", `/api/cms/users/${created.body.user.id}`, { cookie: ownerCookie, body: { action: "disable" } });
    check("disabled editor → 401 on the next request", (await call("GET", "/api/cms/content", { cookie: editorCookie })).status === 401);
    const ownerId = (await call("GET", "/api/auth/me", { cookie: ownerCookie })).body.user.id;
    check("the last owner cannot be demoted", (await call("PATCH", `/api/cms/users/${ownerId}`, { cookie: ownerCookie, body: { action: "set-role", role: "editor" } })).body.error === "last_owner");

    // Rate limit (real Workers rate-limit binding, simulated locally): 10 per minute per username + IP
    const attempts = [];
    for (let index = 0; index < 11; index += 1) attempts.push(await login("owner", "wrong-password-x", { clientIp: "198.51.100.9" }));
    check("11th sign-in in a minute from one IP → 429 (local rate-limit binding)", attempts.slice(0, 10).every((result) => result.status === 401) && attempts[10].status === 429 && attempts[10].headers["retry-after"] === "60", attempts.map((result) => result.status));

    // CPU: a sign-in (PBKDF2 100k) vs /me (no hashing), locally — wall time on an idle machine ≈ CPU (local D1 / KV).
    const time = async (run, count) => { const out = []; for (let index = 0; index < count; index += 1) out.push((await run(index)).ms); return out.sort((a, b) => a - b); };
    const logins = await time(() => login("owner", "owner-password-456"), 8);
    const mes = await time(() => call("GET", "/api/auth/me", { cookie: ownerCookie }), 8);
    const unknown = await time((index) => login(`nobody${index}`, "whatever-password"), 8);
    const median = (list) => list[Math.floor(list.length / 2)];
    const probe = async (path) => { const started = performance.now(); const body = await (await fetch(`${base}${path}`)).json(); return { ms: performance.now() - started, inside: body.insideMs }; };
    const hashes = []; const noops = [];
    for (let index = 0; index < 15; index += 1) { hashes.push(await probe("/__test/hash")); noops.push(await probe("/__test/noop")); }
    const hashCost = median(hashes.map((entry) => entry.ms).sort((a, b) => a - b)) - median(noops.map((entry) => entry.ms).sort((a, b) => a - b));
    const inside = median(hashes.map((entry) => entry.inside).sort((a, b) => a - b));
    console.log(`CPU (wrangler dev --local, workerd on this machine): one PBKDF2-SHA256 100k check ≈ ${hashCost.toFixed(1)} ms (median of 15, hash endpoint minus no-op endpoint; clock inside the Worker says ${inside.toFixed(1)} ms). Whole sign-in ${median(logins).toFixed(1)} ms vs /me ${median(mes).toFixed(1)} ms (includes local D1 / KV writes); unknown-user sign-in ${median(unknown).toFixed(1)} ms (decoy hash).`);
    // Loose bounds on purpose (CI runners are slower): the point is "hashing happens" and "unknown user ≈ real user".
    check("one PBKDF2 check costs real CPU (> 5 ms); an unknown user costs about the same as a real sign-in", hashCost > 5 && hashCost < 400 && Math.abs(median(unknown) - median(logins)) < Math.max(40, median(logins) * 0.6), { hashCost, logins, mes, unknown });

    const audit = await (await fetch(`${base}/__test/audit`)).json();
    const actions = new Set(audit.map((row) => row.action));
    check("audit: bootstrap, login, login_failed, password_change, user_create, user_disable, started, succeeded, denied", ["bootstrap", "login", "login_failed", "password_change", "user_create", "user_disable", "started", "succeeded", "denied"].every((action) => actions.has(action)), [...actions]);
    check("audit holds no password, temporary password or hash", !JSON.stringify(audit).match(/owner-password-456|editor-password-789|bootstrap-test-secret|pbkdf2/) && !JSON.stringify(audit).includes(created.body.temporaryPassword));

    const failed = checks.filter((entry) => !entry.ok);
    assert.deepEqual(failed, [], "every sign-in check passes in wrangler dev --local");
    console.log(`Auth (wrangler dev --local, D1 + KV + rate limits + fake GitHub) OK: ${checks.length} checks passed.`);
  } finally { stop(); }
} finally {
  await github.close();
  rmSync(persist, { recursive: true, force: true });
  rmSync(join(cwd, "generated.mjs"), { force: true });
}
process.exit(0);
